# -*- coding: utf-8 -*-
{
    'name' : 'MSY WHATSAPP Software',
    'version' : '1.1',
    'summary': 'MSY Whatsapp Software',
    'sequence': -100,
    'description': """MSY WHATSAPP SOFTWARE""",
    'category': 'Accounting/Accounting',
    'website': 'https://www.odoo.com/page/billing',
    'depends' : ['sale'],
    'data': ['views/sale.xml',
            'views/sale_whatsapp.xml',
            'views/templates.xml',
             'security/ir.model.access.csv'],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
